apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: intelligent-mobility
  description: Everything related to intelligent-mobility
  title: Intelligent Mobility
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: team-a
